<?php

namespace Epsi\MainBundle\Repository;

/**
 * poi_teamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class poi_teamRepository extends \Doctrine\ORM\EntityRepository
{
}
