<?php

namespace Epsi\MainBundle\Repository;

/**
 * PointOfInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointOfInterestRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(){
        $qb = $this->createQueryBuilder("poi");
        $qb->select("poi, pt, t");
        $qb->leftJoin("poi.poiTeam", "pt");
        $qb->leftJoin("pt.team", "t");
        
        return $qb->getQuery()->getResult();
    }
}
