<?php

namespace Epsi\MainBundle\Repository;

/**
 * PointOfInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointOfInterestRepository extends \Doctrine\ORM\EntityRepository
{
}
